In [33]:
import pandas as pd
train_df =pd.read_csv("dataset/dataset/train.csv")
print("Kich thuoc tep train:", train_df.shape)
print("Danh sach cac cot", list(train_df.columns))
print("="*10)
print("Cac dong du lieu dau tien")
print("="*10)
print(train_df.head(3))
print("="*10)
print("Cac dong du lieu cuoi cung")
print("="*10)
print(train_df.tail(3))

Kich thuoc tep train: (14306, 4)
Danh sach cac cot ['Rating', 'Comment', 'Label', 'SpamLabel']
Cac dong du lieu dau tien
   Rating                                            Comment  Label  SpamLabel
0       5                  Chất lượng sản phẩm tuyệt vời, má      0          0
1       5  Jdjd is a waste of my time and place to ask qu...      1          3
2       5  Dhnxncbcncncncncnncncncnncncncncncncncnncncncj...      1          3
Cac dong du lieu cuoi cung
       Rating                                            Comment  Label  \
14303       5  Sh tư vấn nhiệt tình. \nGiao hàng nhanh chóng....      0   
14304       5  rất hài lòng, giầy đẹp, đi êm chân, giá rẻ, đó...      0   
14305       5  Chất lượng sản phẩm tuyệt vời. Giao hàng nhanh...      0   

       SpamLabel  
14303          0  
14304          0  
14305          0  


In [ ]:
# # 1. Đọc cả 3 tập train, dev, test
# train_df = pd.read_csv('dataset/dataset/train.csv')
# dev_df = pd.read_csv('dataset/dataset/dev.csv')
# test_df = pd.read_csv('dataset/dataset/test.csv')


# print("1. Quy mô tập dữ liệu")

# print(f"- Train: {train_df.shape[0]:,} dòng, {train_df.shape[1]} cột")
# print(f"- Dev (Validation): {dev_df.shape[0]:,} dòng, {dev_df.shape[1]} cột")
# print(f"- Test: {test_df.shape[0]:,} dòng, {test_df.shape[1]} cột")
# total_rows = len(train_df) + len(dev_df) + len(test_df)
# print(f"=> Tổng cộng: {total_rows:,} bản ghi")

# print("2. Chất lượng: Giá trị thiếu (MISSING) tập train")

# missing = train_df.isnull().sum()
# missing_pct = (missing / len(train_df)) * 100
# missing_df = pd.DataFrame({'Số lượng thiếu': missing, 'Tỷ lệ (%)': missing_pct})
# print(missing_df)


# print("3. Chất lượng: Trùng lập (duplicate) tập train")

# dup_full = train_df.duplicated().sum()
# dup_comment = train_df.duplicated(subset=['Comment']).sum()
# print(f"- Số dòng trùng hoàn toàn (tất cả các cột): {dup_full}")
# print(f"- Số dòng trùng nội dung bình luận (Comment): {dup_comment}")

# print("4. PHÂN BỐ NHÃN MỤC TIÊU (LABEL - 0: Non-spam, 1: Spam)")

# label_counts = train_df['Label'].value_counts()
# label_pct = train_df['Label'].value_counts(normalize=True) * 100
# label_dist = pd.DataFrame({'Số lượng': label_counts, 'Tỷ lệ (%)': label_pct})
# print(label_dist)

# print("\n" + "="*40)
# print("5. CHI TIẾT CÁC LOẠI SPAM (SPAMLABEL)")
# print("="*40)
# spam_counts = train_df['SpamLabel'].value_counts()
# spam_pct = train_df['SpamLabel'].value_counts(normalize=True) * 100
# spam_dist = pd.DataFrame({'Số lượng': spam_counts, 'Tỷ lệ (%)': spam_pct})
# print(spam_dist)

import pandas as pd

# 1. Đọc dữ liệu
train_df = pd.read_csv('dataset/dataset/train.csv')
dev_df = pd.read_csv('dataset/dataset/dev.csv')
test_df = pd.read_csv('dataset/dataset/test.csv')

# 2. Quy mô (Số dòng, số cột)
print(train_df.shape, dev_df.shape, test_df.shape)

# 3. Kiểm tra rỗng (Missing)
print(train_df.isnull().sum())


# 4. Kiểm tra trùng lặp
print(train_df.duplicated().sum())

# 5. Phân bố nhãn (0 vs 1)


(14306, 4) (1590, 4) (3974, 4)
Rating       0
Comment      0
Label        0
SpamLabel    0
dtype: int64
0


In [35]:
# 1. Thống kê độ dài từ (Word count) của bình luận
train_df['word_count'] = train_df['Comment'].astype(str).apply(lambda x: len(x.split()))

print("--- THỐNG KÊ ĐỘ DÀI BÌNH LUẬN (SỐ TỪ) ---")
print(train_df['word_count'].describe())

# 2. Phân bố Rating theo nhãn Spam/Non-spam
print("\n--- PHÂN BỐ RATING THEO NHÃN (LABEL) ---")
rating_label = pd.crosstab(train_df['Rating'], train_df['Label'], margins=True)
print(rating_label)

# 3. Xem 2 ví dụ thực tế cho mỗi loại SpamLabel (0, 1, 2, 3)
print("\n--- VÍ DỤ MẪU TỪNG LOẠI NHÃN ---")
for sp_label in sorted(train_df['SpamLabel'].unique()):
    sample = train_df[train_df['SpamLabel'] == sp_label]['Comment'].iloc[0]
    print(f"\n[SpamLabel = {sp_label}]:\n{sample[:120]}...")

--- THỐNG KÊ ĐỘ DÀI BÌNH LUẬN (SỐ TỪ) ---
count    14306.000000
mean        26.067175
std         21.797906
min          1.000000
25%         12.000000
50%         20.000000
75%         34.000000
max        182.000000
Name: word_count, dtype: float64

--- PHÂN BỐ RATING THEO NHÃN (LABEL) ---
Label       0     1    All
Rating                    
1         213    27    240
2          93     8    101
3         193    28    221
4         292    78    370
5        9794  3580  13374
All     10585  3721  14306

--- VÍ DỤ MẪU TỪNG LOẠI NHÃN ---

[SpamLabel = 0]:
Chất lượng sản phẩm tuyệt vời, má...

[SpamLabel = 1]:
Chất lượng sản phẩm tuyệt vời 
Đóng gói sản phẩm chắc chắn
Shop phục vụ rất thích...

[SpamLabel = 2]:
hàng đúng y hình, chưa dùng nên chưa biết chất lượng thế nào, nhưng giao hàng lâu quá!...

[SpamLabel = 3]:
Jdjd is a waste of my time and place to ask questions about assignments and I will be rewarded one way or another culpri...


In [36]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score

train_df = pd.read_csv('dataset/dataset/train.csv')
dev_df = pd.read_csv('dataset/dataset/dev.csv')

# 2. HÀM TRÍCH XUẤT ĐẶC TRƯNG ABSA
aspect_keywords = {
    'aspect_quality': ['chất lượng', 'xịn', 'tốt', 'vải', 'đẹp', 'bền', 'dỏm', 'kém'],
    'aspect_delivery': ['giao hàng', 'vận chuyển', 'ship', 'nhanh', 'chậm', 'đóng gói'],
    'aspect_price': ['giá', 'rẻ', 'đắt', 'tiền', 'voucher', 'xu']
}

def extract_absa_features(text):
    text_lower = str(text).lower()
    features = []
    for aspect, keywords in aspect_keywords.items():
        has_aspect = int(any(kw in text_lower for kw in keywords))
        features.append(has_aspect)
    return features

# 3. TIỀN XỬ LÝ VÀ CHỐNG RÒ RỈ DỮ LIỆU (DATA LEAKAGE)
# Chỉ fit_transform trên tập TRAIN
tfidf = TfidfVectorizer(max_features=500)
X_train_text = tfidf.fit_transform(train_df['Comment']).toarray()
print("X_train_text")
print(X_train_text)
print("==============================")
X_train_rating = (train_df[['Rating']].values - 1) / 4.0
absa_train = np.array([extract_absa_features(c) for c in train_df['Comment']])

X_train = np.hstack([X_train_text, X_train_rating, absa_train])
print("X_train")
print(X_train)
print("==============================")
y_train = train_df['Label'].values
print("y_train", y_train)
print("==============================")
print("absa_train")
print(absa_train)
print("==============================")



# Chỉ transform trên tập DEV (Validation)
X_dev_text = tfidf.transform(dev_df['Comment']).toarray()
X_dev_rating = (dev_df[['Rating']].values - 1) / 4.0
absa_dev = np.array([extract_absa_features(c) for c in dev_df['Comment']])

X_val = np.hstack([X_dev_text, X_dev_rating, absa_dev])
y_val = dev_df['Label'].values

print("Kích thước ma trận huấn luyện (X_train):", X_train.shape)
print("Kích thước ma trận kiểm tra (X_val):", X_val.shape)

# 4. HUẤN LUYỆN MÔ HÌNH CƠ SỞ (BASELINE)
clf = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
clf.fit(X_train, y_train)

# 5. ĐÁNH GIÁ TRÊN TẬP DEV
y_pred = clf.predict(X_val)
print("du doan", y_pred)
print("That   ", y_val)


print("\n--- BÁO CÁO PHÂN LOẠI TRÊN TẬP DEV (CLASSIFICATION REPORT) ---")
print(classification_report(y_val, y_pred, target_names=['0: Non-Spam', '1: Spam']))
print("Macro F1-Score:", round(f1_score(y_val, y_pred, average='macro'), 4))

X_train_text
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
X_train
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 0.]]
y_train [0 1 1 ... 0 0 0]
absa_train
[[1 0 0]
 [0 0 0]
 [0 0 0]
 ...
 [1 1 0]
 [1 1 1]
 [1 1 0]]
Kích thước ma trận huấn luyện (X_train): (14306, 504)
Kích thước ma trận kiểm tra (X_val): (1590, 504)
du doan [0 0 0 ... 0 0 0]
That    [0 0 1 ... 0 0 0]

--- BÁO CÁO PHÂN LOẠI TRÊN TẬP DEV (CLASSIFICATION REPORT) ---
              precision    recall  f1-score   support

 0: Non-Spam       0.90      0.80      0.85      1157
     1: Spam       0.59      0.77      0.67       433

    accuracy                           0.79      1590
   macro avg       0.75      0.78      0.76      1590
weighted avg       0.82      0.79      0.80      1590

Macro F1-Score: 0.7582


In [37]:
# Đếm tỷ lệ phần trăm của từng lớp trong cột Label
train_df['Label'].value_counts(normalize=True) * 100

Label
0    73.989934
1    26.010066
Name: proportion, dtype: float64